### ISSUE TITLE
Error in npm i run

### ISSUE THREAD

**Issue by ps8695** [theoomoregbee/US-visa-appointment-notifier#11]
getting below and nothing is happening after that:
$ npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

**Comment by theoomoregbee** [comment]
You can delete the `package-lock.json` and then run `npm i` again.
