### ISSUE TITLE
TypeError: Cannot read properties of null (reading '$')

### ISSUE THREAD

**Issue by preet1312** [theoomoregbee/US-visa-appointment-notifier#12]
Getting "TypeError: Cannot read properties of null (reading '$')" when running npm start, Kindly help

**Comment by ps8695** [comment]
$ npm i

up to date in 42s

9 packages are looking for funding
  run `npm fund` for details

vv@VNDCCORPHP1893 MINGW64 ~/Desktop/US-visa-appointment-notifier-main
$ npm start

> us-visa-appointment-notifier@1.0.0 start
> node index.js

C:\Users\vv\Desktop\US-visa-appointment-notifier-main\node_modules\puppeteer\lib\cjs\puppeteer\node\ChromeLauncher.js:70
                throw new Error(missingText);
                      ^

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1022525).
    at ChromeLauncher.launch (C:\Users\vv\Desktop\US-visa-appointment-notifier-main\node_modules\puppeteer\lib\cjs\puppeteer\node\ChromeLauncher.js:70:23)
    at async C:\Users\vv\Desktop\US-visa-appointment-notifier-main\index.js:96:19

Node.js v18.14.0

**Comment by theoomoregbee** [comment]
You need to pull the latest changes - this was fixed in https://github.com/theoomoregbee/US-visa-appointment-notifier/pull/2
