### ISSUE TITLE
how we can run this code for any other country to setup the email alert for the appointment? Thanks

### ISSUE THREAD

**Issue by Muhammadwaqas2506** [theoomoregbee/US-visa-appointment-notifier#15]
how we can run this code for any other country to setup the email alert for the appointment? Thanks

_Originally posted by @Muhammadwaqas2506 in https://github.com/theoomoregbee/US-visa-appointment-notifier/issues/3#issuecomment-1436078658_

**Comment by theoomoregbee** [comment]
Follow the readme `Configuration` section and then `How to use it` section. The two things you will need is ur facility and schedule id, which you can get once you sign in to ur account - see `FAQ` section to get those values.
