### ISSUE TITLE
TypeError: Cannot read properties of null (reading '$')

### ISSUE THREAD

**Issue by sush1510** [theoomoregbee/US-visa-appointment-notifier#17]
I have the latest code ,still getting this error

![image](https://user-images.githubusercontent.com/126188037/220973174-fd250912-ece3-473c-8099-f6c41d5621e5.png)
![image](https://user-images.githubusercontent.com/126188037/220973403-a683339f-7971-44d8-8e06-06007aa0dc92.png)

**Comment by theoomoregbee** [comment]
This was fixed in the latest code.
