### ISSUE TITLE
Totally lost

### ISSUE THREAD

**Issue by gbgit136** [theoomoregbee/US-visa-appointment-notifier#20]
I am trying to run this on my Mac.
1. I saved the folder on Desktop
2. I try to run the code on terminal but it isn't working

Could you please help me with the full syntax of what to type in Terminal to run this script from scratch?

I have added the values to config.js and saved it as config.env.
I have created an account on Mailgun, got the API key, and I've  added authorized recipient.

Hoping to hear from you. These could come across as dumb questions, apologies for that. Thanks.

**Comment by theoomoregbee** [comment]
see readme.md
