### ISSUE TITLE
MAILGUN_DOMAIN='mailgun domain' what will be the domain 

### ISSUE THREAD

**Issue by SumitMistry** [theoomoregbee/US-visa-appointment-notifier#21]
I saw your config file[https://github.com/theoomoregbee/US-visa-appointment-notifier/blob/main/.env.example] line-15 asking for MAILGUN_DOMAIN='mailgun domain' but I dont know what value i put it there from the below mailgun info I have...

My mailgun account gave me the following:

> 
> `curl -s --user 'api:b******************************84a-7****************2f' \
> 	 https://api.mailgun.net/v3/sandbox37****************22.mailgun.org/messages \
> 	 -F from='Mailgun Sandbox <postmaster@sandbox37****************22.mailgun.org>' \
> 	 -F to='Sam <**@outlook.com>' \
> 	 -F subject='Hello Sam' \
> 	 -F text='Congratulations Sam, you just sent an email with Mailgun!  You are truly awesome!'

Your guidance will be appreciated. Thank you in advance

**Comment by joaovieira-ca** [comment]
The domain that  I used I found under `Sending->Domains`.  It is the `sandboxXXX.mailgun.org` value.

![image](https://user-images.githubusercontent.com/9250618/227744581-f1a52e64-b930-49a5-93a5-5dbbc0b0df7f.png)

**Comment by theoomoregbee** [comment]
Thanks, @jluiz20.

**Comment by SumitMistry** [comment]
Thanks @jluiz20
