### ISSUE TITLE
Error: Parameter "key" is required

### ISSUE THREAD

**Issue by skyloud22** [theoomoregbee/US-visa-appointment-notifier#24]
There is no api that starts with key--xxxx

the one i could find under the sandbox domain does not seem to work. 

Can you please help to identify which api key to use?

**Comment by dezluan** [comment]
@skyloud22 I had the same issue happen to me, but it was just my fault.
1. Make sure your _env_ file is correctly named, i.e. ".env" (it should have the extension of .env)
2. The key you use is the one under your mailgun dashboard > API Keys > Private Key (it doesn't necessarily have a key- prefix)
