### ISSUE TITLE
The API link doesn't work anymore

### ISSUE THREAD

**Issue by mandeepjandoria** [theoomoregbee/US-visa-appointment-notifier#26]
I think the API link: https://ais.usvisa-info.com/en-ca/niv/schedule/{SCHEDULEID}/appointment/days/Toronto.json?appointments%5Bexpedite%5D=false, doesn't work anymore.

**Comment by theoomoregbee** [comment]
Yeah, I observed this while debuging #25 there's a workaround to get the data since the URL is now not available when the origin is not the ais site

**Comment by theoomoregbee** [comment]
Yeah, I observed this while debugging #25 there's a workaround to get the data since the URL is now not available when the origin is not the ais site. 

There's a workaround which I will find sometime to add.

**Comment by liuyang12** [comment]
@theoomoregbee Can you briefly talk about the idea for the workaround? I need this to work in a rather urgent fashion. I checked the html file `appointment.html` and js file `application-xxx.js` with no idea of the solution.
