### ISSUE TITLE
facility 

### ISSUE THREAD

**Issue by fameka1** [theoomoregbee/US-visa-appointment-notifier#3]
How do I find my own facility id?

**Comment by patzu** [comment]
It is city name I think.

FACILITY_ID='Yerevan'

**Comment by shubhambodhe** [comment]
You can find the facility id by checking the value of the corresponding city in the drop-down.

![image](https://user-images.githubusercontent.com/17024931/209408234-4b342447-911c-4fc7-acc4-d5da18e1f786.png)

**Comment by fameka1** [comment]
> You can find the facility id by checking the value of the corresponding city in the drop-down.
> 
> ![image](https://user-images.githubusercontent.com/17024931/209408234-4b342447-911c-4fc7-acc4-d5da18e1f786.png)

Where can I find it ?

**Comment by theoomoregbee** [comment]
When you get to where you select city, use the browser dev mode to inspect the city dropdown as mentioned here 

> You can find the facility id by checking the value of the corresponding city in the drop-down.
> 
> ![image](https://user-images.githubusercontent.com/17024931/209408234-4b342447-911c-4fc7-acc4-d5da18e1f786.png)

**Comment by fameka1** [comment]
> When you get to where you select city, use the browser dev mode to inspect the city dropdown as mentioned here
> 
> > You can find the facility id by checking the value of the corresponding city in the drop-down.
> > ![image](https://user-images.githubusercontent.com/17024931/209408234-4b342447-911c-4fc7-acc4-d5da18e1f786.png)

The browser does not open when I run the program.

**Comment by fameka1** [comment]
status: 403,
  details: 'Domain sandboxe1164ceef2a340a89c348279b0dde46b.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.'


How do I resolve this error?

**Comment by talasalim** [comment]
My code is currently running for Vancouver but is there a way to check for Calgary as well in an alternative manner?

**Comment by shubhambodhe** [comment]
> My code is currently running for Vancouver but is there a way to check for Calgary as well in an alternative manner?

You can make a copy of the program that you checked out and change the city in that copied program. You should then run it as a new instance.

**Comment by Muhammadwaqas2506** [comment]
how we can run this code for any other country to setup the email alert for the appointment? Thanks
