### ISSUE TITLE
Can it be used without previously scheduled date?

### ISSUE THREAD

**Issue by qomhmd** [theoomoregbee/US-visa-appointment-notifier#32]
Hello. I haven't scheduled a date so far as all the calendar dates are unavailable. Can the script used to notify me whenever any dates become available?

![image](https://github.com/theoomoregbee/US-visa-appointment-notifier/assets/9105400/6d730683-a306-4d5d-b048-293ee67b06c4)

**Comment by theoomoregbee** [comment]
No. It requires you to have a previous appointment.
