### ISSUE TITLE
Failed to parse dates, probably because you are not logged in

### ISSUE THREAD

**Issue by samcookies** [theoomoregbee/US-visa-appointment-notifier#35]
hi there, Im getting the below error, do i need to login somewhere before i run this script, there are my cred saved in the .env.

_**_> us-visa-appointment-notifier@1.0.0 start
> node index.js

=====>>> Step: starting process with 20 tries left
=====>>> Step: logging in
=====>>> Step: checking for schedules
{"message":"Facility is not valid","error":"bad_request"}
Unable to parse page JSON content <html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"message":"Facility is not valid","error":"bad_request"}</pre></body></html>
Failed to parse dates, probably because you are not logged in
Terminate batch job (Y/N)? y_**_

**Comment by theoomoregbee** [comment]
The script will automatically log you in as long as your credentials are in the .env file.
