### ISSUE TITLE
Authorized Recipients

### ISSUE THREAD

**Issue by fameka1** [theoomoregbee/US-visa-appointment-notifier#5]
"status: 403,
  details: 'Domain sandboxe1164ceef2a340a89c348279b0dde46b.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.' "

I added the authorized recipient e-mail address and got it approved, but it still gave the same error.

**Comment by shubhambodhe** [comment]
Can you try with the same sender email address that you tried to create an account with the mailgun. I had this issue and it was resolved when I made that change.

**Comment by theoomoregbee** [comment]
or you can add a test email address in your mailgun sanbox dashboard - see https://help.mailgun.com/hc/en-us/articles/217531258-Authorized-Recipients

**Comment by theoomoregbee** [comment]
updated the readme FAQ with this issue

**Comment by jasdeepece7** [comment]
@theoomoregbee Getting the below error while trying to run the script. Please check and suggest what is wrong and needs to be fixed to make it work:-
=====>>> Step: sending an email to schedule for 02-01-2025
[Error: Unauthorized] { status: 401, details: 'Forbidden' }

I have update the .env file and below values i changed as per my mailgun account:-
NOTIFY_EMAILS='XXXXXXXXXX'
MAILGUN_USERNAME='XXXXXXXXXXX'
MAILGUN_DOMAIN='sandboxdXXXXXXXXXXXXXXXXXXXX.mailgun.org'
MAILGUN_API_KEY='pubkey-XXXXXXXXXXXXXX'

Also, please confirm that for the MAILGUN_USERNAME we need to add our email with which we signedup for mailgun and for MAILGUN_API_KEY we need to add pubkey value from our accounts API Keys section, as i didn't find any value starting only with key-xxxxxx

**Comment by zehao-ba** [comment]
Hello, i am having this error when i run 'npm start':


Error: Parameter "key" is required
    at new _ (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:32862)
    at e.client (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:58416)
    at Object.<anonymous> (/Users/xxx/Desktop/US-visa-appointment-notifier-main/utils.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/xxx/Desktop/US-visa-appointment-notifier-main/index.js:5:37)

My env is setting as:
NOTIFY_EMAILS='email@gmail.com'
MAILGUN_USERNAME='email@gmail.com'
MAILGUN_DOMAIN='sandboxaxxxx.mailgun.org'
MAILGUN_API_KEY='pubkey-xxxx'

**Comment by simonesaggiatore** [comment]
> Hello, i am having this error when i run 'npm start':
> 
> Error: Parameter "key" is required at new _ (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:32862) at e.client (/Users/xxx/Desktop/US-visa-appointment-notifier-main/node_modules/mailgun.js/mailgun.node.js:2:58416) at Object. (/Users/xxx/Desktop/US-visa-appointment-notifier-main/utils.js:6:20) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Module.require (node:internal/modules/cjs/loader:1235:19) at require (node:internal/modules/helpers:176:18) at Object. (/Users/xxx/Desktop/US-visa-appointment-notifier-main/index.js:5:37)
> 
> My env is setting as: NOTIFY_EMAILS='[email@gmail.com](mailto:email@gmail.com)' MAILGUN_USERNAME='[email@gmail.com](mailto:email@gmail.com)' MAILGUN_DOMAIN='sandboxaxxxx.mailgun.org' MAILGUN_API_KEY='pubkey-xxxx'

I have the same error here. 

There are 3 types of API_KEY: 1) Mailgun API keys, for example, 8fff941a7a43bcc4c45517a4a0204f11-d010bdaf-47f054a6 ; 2) Last Segments of the Mailgun API Key, for example, d010bdaf-47f054a6 ; 3) Verification public key: begins with pubkey-xxxx. It only works with their deprecated v3 validations endpoint. If users want to use Validations via API, please use the v4 validations endpoint and create a Mailgun API key above.

How do I resolve this error?
