### ISSUE TITLE
Where is my shcedule ID?

### ISSUE THREAD

**Issue by bartodt** [theoomoregbee/US-visa-appointment-notifier#7]
Hi, i am trying to run the project but i cant find my shcedule id in the visa website. Where i can find it?

Thank you.

**Comment by BennyDanielT** [comment]
You can find it in the URL, when you attempt to reschedule your appointment. Let me know if you can't find it.

**Comment by shubhambodhe** [comment]
> Hi, i am trying to run the project but i cant find my shcedule id in the visa website. Where i can find it?
> 
> Thank you.

![image](https://user-images.githubusercontent.com/17024931/211177553-71e6a388-e800-43d7-b116-3c8c5a8c3a4e.png)

The highlighted text in the snapshot would be your schedule id.
