### ISSUE TITLE
"No available appointments" banning? 

### ISSUE THREAD

**Issue by karttikeya** [theoomoregbee/US-visa-appointment-notifier#9]
Hi, 

First, thanks a lot for the repo. It is indeed still working and quite simple to setup/modify. 

I am curious what search rate is recommended to use? I often notice that while I have the script running, the website shows "no available appointments" when checked through the browser and I wonder if it is some sort of a DDoS protection mechanism that simply shuts down on rate querying?

**Comment by talasalim** [comment]
I'm wondering how you got the mailgun key? Its not on my dashboard and when I go to API keys there is private, public keys but non of them start with key-****

**Comment by karttikeya** [comment]
I used the key under the sandbox domain name with "API Key" against it. It does not begin with key-*** in my interface but works fine regardless.

**Comment by talasalim** [comment]
Thats weird I don't have that showing for me. It just shows sandbox domain on its own so instead I clicked on API keys and copied the private key from there but its showing me an error. 

Another question, sorry to bother you. There is nothing to edit on the config file right? I just made a .env file but had to give it a name cuz it can't be an extension on its own so I'm not sure if that is why its giving me errors?

**Comment by karttikeya** [comment]
just .env works fine. I simply followed the instructions in readme, they all work.

**Comment by theoomoregbee** [comment]
hey @karttikeya for me I used the below config in my `.env` to pull data:

```sh
MAX_NUMBER_OF_POLL=1000
NEXT_SCHEDULE_POLL=10000
```

**Comment by talasalim** [comment]
Hey @theoomoregbee this means that your code runs for less than 3 hours a day right? I had set NEXT_SCHEDULE_POLL=396000 so that is can run all day while maintaining the limit of 250 but now it does now show me any available slots like @karttikeya

**Comment by karttikeya** [comment]
@talasalim what is the 250 limit? source?

**Comment by talasalim** [comment]
@karttikeya well some websites say you can only check 4 times a day but I assumed 250 because of the default in the config file. I also read online that checking too frequently can get you banned for 72 hours, so I hope that's not the case.. Not sure what's the ideal wait time..

**Comment by karttikeya** [comment]
IMO the no available appointments get resolved in about 12 hours. but it does occur again frequently. 

curious what other strategies are?

**Comment by theoomoregbee** [comment]
closing this for now, we can revisit if there are other strategies around the appointments availability.
